// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH9zc7ObxRvWEZLLF1hEhjaSsJ3hcZicM',
    appId: '1:1041140888494:web:7e27659a063ddadede4e3f',
    messagingSenderId: '1041140888494',
    projectId: 'flutterloginapp-51a24',
    authDomain: 'flutterloginapp-51a24.firebaseapp.com',
    storageBucket: 'flutterloginapp-51a24.firebasestorage.app',
    measurementId: 'G-N56842KZMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuGZIXJIlbvGdKudTPX65E7p7eqv6SE28',
    appId: '1:1041140888494:android:17a452ea192ad30ade4e3f',
    messagingSenderId: '1041140888494',
    projectId: 'flutterloginapp-51a24',
    storageBucket: 'flutterloginapp-51a24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEisxfkti6e2OAnqqpTJ5b0IINGvQbE9E',
    appId: '1:1041140888494:ios:ad204dc58e87f5dfde4e3f',
    messagingSenderId: '1041140888494',
    projectId: 'flutterloginapp-51a24',
    storageBucket: 'flutterloginapp-51a24.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEisxfkti6e2OAnqqpTJ5b0IINGvQbE9E',
    appId: '1:1041140888494:ios:ad204dc58e87f5dfde4e3f',
    messagingSenderId: '1041140888494',
    projectId: 'flutterloginapp-51a24',
    storageBucket: 'flutterloginapp-51a24.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH9zc7ObxRvWEZLLF1hEhjaSsJ3hcZicM',
    appId: '1:1041140888494:web:cb344dc2996a3dafde4e3f',
    messagingSenderId: '1041140888494',
    projectId: 'flutterloginapp-51a24',
    authDomain: 'flutterloginapp-51a24.firebaseapp.com',
    storageBucket: 'flutterloginapp-51a24.firebasestorage.app',
    measurementId: 'G-FDDKQZEBNX',
  );

}